package-lock.json
package.json
src/components/app.js
src/components/chart.js
src/components/login.js
src/components/run_map/run_map.js
src/components/signup.js
src/index.js

we will deal with the login routing when we learn how to do it

completed routing

---

src/components/app.js
src/components/app_header/app_header.scss
src/components/nav_folder/map_nav/map_nav.js
src/components/nav_folder/map_nav/map_nav.scss
src/components/nav_folder/map_nav/package.json
src/components/run_map/run_map.js
src/components/run_map/run_stats.js

created nav folder

---

package-lock.json
public/api/config.php
public/api/functions.php
public/api/getmiles.php
public/api/sessiontest.php
public/api/test.php

The only file that I worked on is **getmiles.php**, format change for all the other files

Started on get miles endpoint

---

public/api/dummydata/datadump0424.sql
public/api/dummydata/getuser.json
public/api/getuser.php
public/api/signup.php

added gender, age, height, weight,
updated dummydata, getuser.php, and signup.php

added the following stats to users,

---

public/api/addpermile.php
public/api/addrun.php
public/api/get_run_dates.php
public/api/get_runsession_results.php
public/api/get_table_data.php
public/api/getpermile.php
public/api/getrunstats.php
public/api/getuser.php
public/api/login.php
public/api/personalbestquery.php
public/dist/check-auth.php
src/actions/types.js
src/components/account/account_routes.js
src/components/account/login/login_form.js
src/components/account/login/submit.js
src/components/account/login/submit_validation_form.js
src/components/account/sign_up/signup_form.js
src/components/general/input.js

Added checkeduserloggedin.php to every endpoint

---

public/api/checkuserloggedin.php

deleted the print statement at the end of checkuserloggedin.php

fixed the dev branch

---

public/api/checkuserloggedin.php
public/api/get_run_dates.php
public/api/getuser.php
public/api/login.php
src/components/account/login/login_form.js
src/components/account/sign_up/signup_form.js
src/components/nav_folder/run_nav.js

Also made few minor typo changes

Made changes to checkeduserloggedin php

---

public/api/get_last_runsession_results.php
public/api/get_runsession_results.php
src/components/run_map/last_run_result.js
src/components/run_map/run_results.js
src/components/run_map/run_results.scss

circles now render dynamically

---

public/api/run-count.php
src/components/run_map/run_results.js
src/components/run_map/run_results.scss
src/components/total_stats/total_stats.js
src/components/total_stats/total_stats.scss

created query to gather total run, monthly run, weekly run count

---

public/api/delete_table_data.php
public/api/postman/delete_table_data
src/components/account/login/login.scss
src/components/general/input.js
src/components/total_stats/table.js

tested on postman that it is working

Completed delete query backend

---

src/components/account/login/login.js
src/components/account/login/login.scss
src/components/nav_folder/nav.scss
src/components/run_map/run_map.js
src/components/runs/runs.scss

removed arrows on login
fixed background img

 cleaned nav bar

---

src/components/nav_folder/map_nav.js
src/components/nav_folder/nav.scss
src/components/nav_folder/run_nav.js
src/components/run_map/run_map.js

removed total/month/week from per mile table

---

package-lock.json
package.json
public/api/add_event.php
public/api/get_event.php
src/components/total_stats/countdown.js
src/components/total_stats/event_date.js
src/components/total_stats/modal/modal.js
src/components/total_stats/total_stats.scss

implementation of event date completed

---

src/components/nav_folder/nav.scss
src/components/total_stats/countdown.js
src/components/total_stats/event_date.js
src/components/total_stats/modal/modal.js
src/components/total_stats/total_stats.scss

changed countdowntimer

---

src/components/total_stats/table.js
src/components/total_stats/total_stats.scss

new media query created for table

---

src/components/account/account_routes.js
src/components/account/login/login.js
src/components/account/sign_up/signup_form.js
src/components/general/input.js

new user properly adding to database

fixed issue with signup getting stuck on loading screen,

---

public/api/delete_guest_event.php
src/components/account/login/login.js
src/components/total_stats/countdown.js
src/components/total_stats/event_date.js
src/components/total_stats/modal/modal.js
src/components/total_stats/tabledata.js

timer now renders at the start

guest run now deletes countdown event on new log in

---

src/components/nav_folder/nav.scss
src/components/nav_folder/tutorial_nav.js
src/components/runs/runs.scss
src/components/total_stats/modal/table_modal.js

fixed modal landscape
fixed modal sizing

fixed formattaing landscape

---

src/components/account/login/login.scss

changed button sizing in landscape view

Corrected input fields that flowed outside of modal,

---

src/components/account/login/login.scss
src/components/account/login/login_form.js
src/components/account/sign_up/signup_form.js

edit size of login and signup buttons in landscape mode

changed titles of input containers to login and signup

---

package-lock.json
package.json
src/components/nav_folder/demo.js
src/components/nav_folder/demo_run.js
src/components/nav_folder/map_nav.js
src/components/nav_folder/nav.scss
src/components/nav_folder/tutorial_nav.js
src/components/nav_folder/tutorial_video.scss
src/style.scss

added responsiveness
music stops when modal closes

new media for tutorial
